### PR TITLE
Add the unstable branch?

### PR DESCRIPTION
**Pull request by Ark74**
Hi, would you consider addin the kdenlive based on Debian Unstable.
Cheers

### CODE REVIEW

**Comment by lvm** [comment]
There are a couple of issues with this PR:

* Why do you install more than one time the same package? (Lines 17 and 23)
* Why do you need vlc or breeze-icon-theme?
* Why are there multiple `RUN` commands? try to use one for all
* After installing multiple packages, try to clean the cache
* The README points to your repo and other docker images which are not the one from this repo
* Not really sure about replacing the stable branch for an unstable one 

Perhaps if you fix the issues with the PR, we could create an unstable branch besides the stable one. But for the moment, I'm not convinced.

Thanks.

**Comment by Ark74** [comment]
Hi,

1. fixed
2. kdenlive complained they were not installed
3. done
4. done
5. in case we can't work this out, i'll change it.
6. my sugestion is to add a branch not replace master.

Bulding to test, let you know any news.
Hope this could help on getting there.

Cheers

**Comment by Ark74** [comment]
After the last changes, it built correctly and the image is even smaller, just a few, but smaller. ;)
Do you see any other issue?

**Comment by lvm** [comment]
That's the problem: I don't see any changes from you first commit on this pull request.  
Have you pushed them?

**Comment by lvm** [comment]
Closing this in favor of #4.

**Pull request closed without merging**
